version: '3.8'

services:
  cross-chain-indexer:
    build: .
    container_name: cross-chain-indexer
    ports:
      - "8080:8080"
    environment:
      # JWT配置
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      
      # 管理员地址列表（逗号分隔）
      - ADMIN_ADDRESSES=${ADMIN_ADDRESSES:-0x27f9B6A7C1Fd66AC4D0e76a2d43B35e8590165f6}
      
      # 商家地址列表（逗号分隔）
      - MERCHANT_ADDRESSES=${MERCHANT_ADDRESSES:-0x77Ed7f6455FE291728A48785090292e3D10F53Bb}
      
      # 数据库配置
      - DB_PATH=/app/data/indexer.db
      
      # 日志级别
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # 区块链RPC配置
      - RPC_URL=${RPC_URL:-https://sepolia.base.org}
      
    volumes:
      # 数据持久化
      - ./data:/app/data
      
      # 日志持久化
      - ./logs:/app/logs
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    
    # 网络配置
    networks:
      - indexer-network

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: cross-chain-indexer-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - cross-chain-indexer
    restart: unless-stopped
    networks:
      - indexer-network

  # Prometheus监控（可选）
  prometheus:
    image: prom/prometheus:latest
    container_name: cross-chain-indexer-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - indexer-network

  # Grafana仪表板（可选）
  grafana:
    image: grafana/grafana:latest
    container_name: cross-chain-indexer-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    restart: unless-stopped
    networks:
      - indexer-network

# 网络配置
networks:
  indexer-network:
    driver: bridge

# 数据卷
volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
