[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_oapp = "HNN4sosaGHuaoi5k1hRHtB1Cae3DQUV9qBXDCNcRoC3M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/zth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 sdk/tests/**/*.test.ts"
